config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  resources :queries, :themes, :answers
  resources :choices, only: [:new, :create, :edit, :update, :destroy]
  resources :users, only: [:show, :index, :update]
  root to: 'pages#home'

end

app/models/theme.rb
class Theme < ActiveRecord::Base
  has_many :queries, dependent: :restrict_with_error
  has_many :choices, through: :queries
  has_many :answers, through: :queries
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController

  before_action :find_theme, only: [:show, :edit, :update, :destroy]
  before_action :verify_editor_rights
  before_action :set_reminder, only: :new

  def show
  end

  def index
    @themes = Theme.order(:name)
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(theme_params)
    if @theme.save
      redirect_to theme_path(@theme)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @theme.update(theme_params)
      redirect_to theme_path(@theme)
    else
      render :edit
    end
  end

  def destroy
    if @theme.destroy
      redirect_to themes_path
    else
      redirect_to themes_path, alert: 'Suppression impossible'
    end
  end

  private

  def find_theme
    @theme = Theme.find(params[:id])
  end

  def theme_params
    params.require(:theme).permit(:name, :description)
  end

  def set_reminder
    @reminder = Theme.order(:name).map(&:name)
  end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<div class="all-form-content">

  <h1 class="text-center"><%= title %></h1>
  <% if reminder %>
    <% count = reminder.count %>
    <div class="all-form-reminder">
      <i>
        <% if count > 1 %>
          <p><%= count %> thèmes enregistrés :
        <% elsif count == 0 %>
          <p>Aucun thème enregistré
        <% else %>
          <p><%= count %> thème enregistré :
        <% end %>
          <%= reminder.join(', ') %></p>
      </i>
    </div>
  <% end %>

  <%= simple_form_for(@theme) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'Soumettre' %>
    </div>
  <% end %>

</div>

app/views/themes/edit.html.erb
<div class="bg-full all-form-layout-new flex-center">
  <%= render "themes/form", title: "Modifier le thème", reminder: nil %>
</div>

app/views/themes/index.html.erb
<!-- BANNER -->
<div class="page-banner page-banner-notebook">
  <div class="page-banner-title">
    <h1>Thèmes enregistrés</h1>
    <% total = @themes.length %>
    <% if total > 1 %>
      <p><%= total %> thèmes trouvés</p>
    <% elsif total == 0 %>
      <p>Aucun thème trouvé</p>
    <% else %>
      <p><%= total %> thème trouvé</p>
    <% end %>
  </div>
</div>
<!-- BANNER -->

<!-- BODY -->
<div class="container">
  <div class="round-button-container padded">
    <!-- ACTION BUTTON -->
    <%= link_to new_theme_path, class: 'round-button-new-element-link' do %>
      <div class="round-button round-button-center round-button-right bg-blue flex-center">
        <p><i class="fa fa-plus" aria-hidden="true"></i></p>
        <div class="round-button-new-element bg-blue">
          Ajouter un thème
        </div>
      </div>
    <% end %>
    <!-- ACTION BUTTON -->
    <h2>Liste des thèmes</h2>
    <% @themes.each_with_index do |theme, index| %>
      <!-- THEME INSTANCE -->
      <div class="list-instance-container">
        <div class="list-instance-item list-instance-id">
          <%= index + 1 %>
        </div>
        <hr>
        <div class="list-instance-item list-instance-name section-title section-title-small">
          <%= theme.name %>
          <% count = theme.queries.count %>
          <% if count > 1 %>
            <p><%= count %> questions</p>
          <% else %>
            <p><%= count %> question</p>
          <% end %>
        </div>
        <hr>
        <div class="list-instance-item list-instance-description">
          <%= theme.description %>
        </div>
        <hr>
        <div class="list-instance-item list-instance-actions">
          <%= link_to theme_path(theme) do %>
            <i class="fa fa-eye" aria-hidden="true" id="show"></i>
          <% end %>
          <%= link_to edit_theme_path(theme) do %>
            <i class="fa fa-pencil" aria-hidden="true" id="edit"></i>
          <% end %>
          <%= link_to theme_path(theme), method: :delete do %>
            <i class="fa fa-trash-o" aria-hidden="true" id="delete"></i>
          <% end %>
        </div>
      </div>
      <!-- THEME INSTANCE -->
    <% end %>
  </div>
</div>
<!-- BODY -->

app/views/themes/new.html.erb
<div class="bg-full all-form-layout-new flex-center">
  <%= render "themes/form", title: "Ajouter un nouveau thème", reminder: @reminder %>
</div>

app/views/themes/show.html.erb
<!-- BANNER -->
<div class="page-banner page-banner-notepad">
  <div class="page-banner-title">
    <h1><%= @theme.name %></h1>
    <% queries = @theme.queries %>
    <% total = queries.length %>
    <% if total > 1 %>
      <p><%= total %> questions trouvées</p>
    <% elsif total == 0 %>
      <p>Aucune question trouvée</p>
    <% else %>
      <p><%= total %> question trouvée</p>
    <% end %>
  </div>
</div>
<!-- BANNER -->

<!-- BODY -->
<div class="container">
  <div class="round-button-container padded">

    <!-- ACTION BUTTONS -->
    <%= link_to edit_theme_path(@theme), class: 'round-button-new-element-link' do %>
      <div class="round-button round-button-top round-button-right bg-blue flex-center">
        <p><i class="fa fa-cog" aria-hidden="true"></i></p>
        <div class="round-button-new-element bg-blue">
          Modifier le thème
        </div>
      </div>
    <% end %>
    <%= link_to theme_path(@theme), method: :delete, class: 'round-button-new-element-link' do %>
      <div class="round-button round-button-center round-button-right bg-red flex-center">
        <p><i class="fa fa-minus" aria-hidden="true"></i></p>
        <div class="round-button-new-element bg-red">
          Supprimer le thème
        </div>
      </div>
    <% end %>
    <%= link_to new_query_path(theme: @theme.id), class: 'round-button-new-element-link' do %>
      <div class="round-button round-button-bottom round-button-right bg-green flex-center">
        <p><i class="fa fa-plus" aria-hidden="true"></i></p>
        <div class="round-button-new-element bg-green">
          Ajouter une question
        </div>
      </div>
    <% end %>
    <!-- ACTION BUTTONS -->

    <div class="section-title">
      <% if @theme.description.length > 0 %>
        <p class='section-title-description'><%= @theme.description %></p>
      <% else %>
        <p class="section-title-description">Aucune description fournie</p>
      <% end %>
    </div>

    <div class="padded-sm">
      <% if queries.empty? %> <!-- check if theme has related queries -->
        <p>Aucune question enregistrée</p>
      <% else %>
        <% queries.each_with_index do |query, index| %>
          <!-- QUERY INSTANCE -->
          <div class="list-instance-container">
            <div class="list-instance-item list-instance-id">
              <%= index + 1 %>
            </div>
            <hr>
            <div class="list-instance-item list-instance-content">
              <%= query.content.html_safe %>
            </div>
            <hr>
            <div class="list-instance-item list-instance-description">
              <%= query.description %>
            </div>
            <hr>
            <div class="list-instance-item list-instance-actions">
              <%= link_to query_path(query) do %>
                <i class="fa fa-eye" aria-hidden="true" id="show"></i>
              <% end %>
              <%= link_to edit_query_path(query) do %>
                <i class="fa fa-pencil" aria-hidden="true" id="edit"></i>
              <% end %>
              <%= link_to query_path(query), method: :delete do %>
                <i class="fa fa-trash-o" aria-hidden="true" id="delete"></i>
              <% end %>
            </div>
          </div>
          <!-- QUERY INSTANCE -->
        <% end %>
      <% end %>
    </div>

  </div>
</div>
<!-- BODY -->