config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  resources :queries, :themes, :answers
  resources :choices, only: [:new, :create, :edit, :update, :destroy]
  resources :users, only: [:show, :index, :update]
  root to: 'pages#home'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="container navbar-container">


    <!-- LOGO -->
    <%= link_to 'Nuances', root_path, class: 'navbar-title' %>
    <!-- LOGO -->


    <!-- DROPDOWN MENU -->
    <div class="navbar-elements">

      <!-- SIGNED IN -->
      <% if user_signed_in? %>
        <div class="navbar-item navbar-dropdown">
          <i class="fa fa-bars" data-toggle="collapse" data-target="#dropdown-menu" aria-expanded="false" aria-controls="dropdown-menu" aria-hidden="true"></i>
        </div>

        <div class="navbar-dropdown-menu collapse" id="dropdown-menu">
          <%= link_to 'Mon profil', user_path(current_user), class: "navbar-item navbar-dropdown-menu-item" %>
          <%= link_to 'Me déconnecter', destroy_user_session_path, method: :delete, class: "navbar-item navbar-dropdown-menu-item" %>
          <% if current_user.editor %>
            <hr>
            <%= link_to 'Dashboard', admin_root_path, class: "navbar-item navbar-dropdown-menu-item" if current_user.admin %>
            <%= link_to 'Thèmes', themes_path, class: "navbar-item navbar-dropdown-menu-item" %>
            <%= link_to 'Questions', queries_path, class: "navbar-item navbar-dropdown-menu-item" %>
          <% end %>
        </div>
      <!-- SIGNED IN -->

      <!-- NOT SIGNED IN -->
      <% else %>
        <%= link_to 'Me connecter', new_user_session_path, class: "navbar-item navbar-item-bordered" %>
        <%= link_to "M'enregistrer", new_registration_path(User.new), class: "navbar-item navbar-item-bordered navbar-item-inverted hidden-xs" %>
      <% end %>
      <!-- NOT SIGNED IN -->

    </div>
    <!-- DROPDOWN MENU -->

  </div>
</div>

app/views/shared/_user_card.html.erb
<div class="user-card flex-center">
  <div class="user-card-inner">
    <p class="user-card-nickname" id="top"><%= user.nickname %></p>
    <p class="user-card-nickname" id="bottom"><%= user.nickname %></p>
    <ul class="user-card-badges">
      <% @themes.each do |theme| %>
        <% bg = @backgrounds.sample %>
        <li class="user-card-badges-badge <%= bg %>">
          <div class="user-card-badges-name <%= bg %>"><%= theme[:name] %></div>
          <%= theme[:queries] %>
        </li>
      <% end %>
    </ul>
    <div class="user-card-pusher"></div>
    <%= cl_image_tag user.photo, height: 150, width: 150, crop: :fill, class: 'user-card-photo' %>
    <div class="user-card-pusher"></div>
  </div>
</div>