config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  resources :queries, :themes, :answers
  resources :choices, only: [:new, :create, :edit, :update, :destroy]
  resources :users, only: [:show, :index, :update]
  root to: 'pages#home'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :query
  belongs_to :choice
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action only: :new do
    reset_queries
    set_query
  end
  before_action :find_query, only: [:show, :edit]

  def show
  end

  def index
  end

  def new
  end

  def create
    @answer = Answer.new(answer_params.merge(user_id: current_user.id))
    if @answer.save
      redirect_to new_answer_path
    else
      redirect_to new_answer_path, alert: 'Une erreur est survenue'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def reset_queries
    case params[:reset]
    when 'all'
      Query.where(validated: true).each do |query|
        query.answers.where(user_id: current_user.id).destroy_all
      end
    end
  end

  def set_query
    queries = Array.new
    answered_queries = Array.new
    validated_queries = Query.where(validated: true)
    validated_queries.each do |query|
      if query.users.include?(current_user)
        answered_queries << query
      else
        queries << query
      end
    end
    @total = validated_queries.count
    @count = answered_queries.count + 1
    if queries.empty?
      attributes = {
        content: 'Vous avez répondu à toutes les questions disponibles',
        description: "Nous tâchons d'ajouter régulièrement de nouvelles questions
                      pour vous permettre d'améliorer votre positionnement et de vous
                      confronter à de nouveaux sujets. Dans l'intervalle, vous êtes libres
                      de recommencer l'ensemble des questions et de découvrir le positionnement
                      des autres utilisateurs"
      }
      @query = Query.new(attributes)
    else
      @query = queries.sample
    end
  end

  def find_query
    @query = Query.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:query_id, :choice_id)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/edit.html.erb
<h1>Answers#edit</h1>
<p>Find me in app/views/answers/edit.html.erb</p>

app/views/answers/index.html.erb
<h1>Answers#index</h1>
<p>Find me in app/views/answers/index.html.erb</p>

app/views/answers/new.html.erb
<div class="marged-top padded-sm">
  <div class="container">
    <div class="row">

      <!-- LEFT: QUERY DETAILS -->
      <div class="col-xs-12 col-md-5">
        <h1 class="question-title"><%= @query.content.html_safe %></h1>
        <p class='question-description'><%= @query.description %></p>
        <% unless [nil, ''].include?(@query.see_more) %>
          <p class="question-know-more">
            <%= link_to 'En savoir plus', @query.see_more, target: '_blank' %>
          </p>
        <% end %>
      </div>
      <!-- LEFT: QUERY DETAILS -->

      <!-- RIGHT: CHOICES -->
      <div class="col-xs-12 col-md-7">
        <% if @query.content == 'Vous avez répondu à toutes les questions disponibles' %>
          <div class="choices-group marged-bottom">
            <%= link_to users_path do %>
              <div class="choices-group-item choices-group-item-users text-center bg-dark-blue">
                <b>EUX</b>
                <p>Ce qu'ils en pensent</p>
              </div>
            <% end %>
            <%= link_to new_answer_path(reset: :all) do %>
              <div class="choices-group-item choices-group-item-users text-center bg-blue">
                <b>MOI</b>
                <p>Répondre à nouveau</p>
              </div>
            <% end %>
          </div>
        <% else %>
          <div class="choices-group marged-bottom">
            <% @query.choices.each do |choice| %>
              <%= link_to answers_path(answer: { query_id: @query.id, choice_id: choice.id }), method: :create do %>
                <div class="choices-group-item bg-blue">
                  <p><%= choice.content %></p>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <!-- RIGHT: CHOICES -->

    </div>
  </div>
</div>

<!-- BOTTOM BANNER -->
<% if @query.content == 'Vous avez répondu à toutes les questions disponibles' %>
  <div class="text-center padded-sm bg-red to-bottom top-buffer">Plus de question disponible</div>
<% else %>
  <div class="text-center padded-sm bg-green to-bottom top-buffer">Question <%= @count %> sur <%= @total %></div>
<% end %>
<!-- BOTTOM BANNER -->

app/views/answers/show.html.erb
<h1>Answers#show</h1>
<p>Find me in app/views/answers/show.html.erb</p>