config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  resources :queries, :themes, :answers
  resources :choices, only: [:new, :create, :edit, :update, :destroy]
  resources :users, only: [:show, :index, :update]
  root to: 'pages#home'

end

app/models/query.rb
class Query < ActiveRecord::Base
  belongs_to :theme
  has_many :answers, dependent: :restrict_with_error
  has_many :choices, dependent: :destroy
  has_many :users, through: :answers

  def name
    content
  end
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController

  before_action :find_query, only: [:show, :edit, :update, :destroy]
  before_action :find_theme, only: :new
  before_action :verify_editor_rights

  def show
    @choice = Choice.new
  end

  def index
    @queries = Query.order(:content)
    @themes = Theme.order(:name)
  end

  def new
    if @theme
      @query = Query.new(theme_id: @theme.id)
    else
      @query = Query.new
    end
  end

  def create
    @query = Query.new(query_params)
    @query.content.gsub!(' ?', '&nbsp;?')
    if @query.save
      redirect_to query_path(@query)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @query.update(query_params)
      redirect_to query_path(@query)
    else
      render :edit
    end
  end

  def destroy
    if @query.destroy
      redirect_to queries_path
    else
      redirect_to queries_path, alert: 'Suppression impossible'
    end
  end

  private

  def find_theme
    @theme = Theme.find(params[:theme]) if params[:theme]
  end

  def find_query
    @query = Query.find(params[:id])
  end

  def query_params
    params.require(:query).permit(:theme_id, :content, :description, :see_more, :validated)
  end
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/queries/_form.html.erb
<div class="all-form-content">
  <h1 class="text-center"><%= title %></h1>

  <%= simple_form_for(@query) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.association :theme, :include_blank => false %>
      <%= f.input :content %>
      <%= f.input :description %>
      <%= f.input :see_more %>
      <%= f.input :validated if params[:action] == 'edit' && @query.choices.count >= 2 %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'Soumettre' %>
    </div>
  <% end %>

</div>

app/views/queries/edit.html.erb
<div class="bg-full all-form-layout-new flex-center">
  <%= render "queries/form", title: 'Modifier la question' %>
</div>

app/views/queries/index.html.erb
<!-- BANNER -->
<div class="page-banner page-banner-notebook">
  <div class="page-banner-title">
    <h1>Questions enregistrées</h1>
    <% total = @queries.length %>
    <% if total > 1 %>
      <p><%= total %> questions trouvées</p>
    <% elsif total == 0 %>
      <p>Aucune question trouvée</p>
    <% else %>
      <p><%= total %> question trouvée</p>
    <% end %>
  </div>
</div>

<!-- BODY -->
<div class="container">
  <div class="round-button-container padded">


    <!-- ACTION BUTTON -->
    <%= link_to new_query_path, class: 'round-button-new-element-link' do %>
      <div class="round-button round-button-center round-button-right bg-green flex-center">
        <p><i class="fa fa-plus" aria-hidden="true"></i></p>
        <div class="round-button-new-element bg-green">
          Ajouter une question
        </div>
      </div>
    <% end %>

    <!-- THEME -->
    <% @themes.each do |theme| %>
      <% queries = theme.queries %>
      <!-- check if theme as queries associated -->
      <% unless queries.empty? %>

        <div class="section-title">
          <h2><%= theme.name %></h2>
          <% count = queries.count %>
          <% if count > 1 %>
            <p id='subtitle'><%= count %> questions</p>
          <% else %>
            <p id='subtitle'><%= count %> question</p>
          <% end %>
        </div>

        <!-- QUERY INSTANCE -->
        <% queries.each_with_index do |query, index| %>
          <div class="list-instance-container">
            <div class="list-instance-item list-instance-id">
              <%= index + 1 %>
            </div>
            <hr>
            <div class="list-instance-item list-instance-content section-title section-title-small">
              <%= query.content.html_safe %>
              <% status =  %>
              <p>
                <%= query.choices.count %> choix
                 -
                <% if query.validated %>
                  <span class="blue-text">Validée</span> <i class="fa fa-check-circle blue-text" aria-hidden="true"></i>
                <% else %>
                  <span class="red-text">En attente</span> <i class="fa fa-times-circle red-text" aria-hidden="true"></i>
                <% end %>
              </p>
            </div>
            <hr>
            <div class="list-instance-item list-instance-description">
              <%= query.description %>
            </div>
            <hr>
            <div class="list-instance-item list-instance-actions">
              <%= link_to query_path(query) do %>
                <i class="fa fa-eye" aria-hidden="true" id="show"></i>
              <% end %>
              <%= link_to edit_query_path(query) do %>
                <i class="fa fa-pencil" aria-hidden="true" id="edit"></i>
              <% end %>
              <%= link_to query_path(query), method: :delete do %>
                <i class="fa fa-trash-o" aria-hidden="true" id="delete"></i>
              <% end %>
            </div>
          </div>
        <% end %>
        <!-- QUERY INSTANCE -->

      <% end %>
      <!-- check if theme as queries associated -->

    <% end %>
    <!-- THEME -->

  </div>
</div>
<!-- BODY -->

app/views/queries/new.html.erb
<div class="bg-full all-form-layout-new flex-center">
  <%= render "queries/form", title: 'Ajouter une nouvelle question' %>
</div>

app/views/queries/show.html.erb
<!-- BANNER -->
<div class="page-banner page-banner-notepad">
  <div class="page-banner-title">
    <h1><%= @query.content.html_safe %></h1>
    <% choices = @query.choices %>
    <% total = choices.length %>
    <% if total > 1 %>
      <p><%= total %> choixs trouvés</p>
    <% elsif total == 0 %>
      <p>Aucun choix trouvé</p>
    <% else %>
      <p><%= total %> choix trouvé</p>
    <% end %>
  </div>
</div>
<!-- BANNER -->

<!-- BODY 1 -->
<div class="container">
  <div class="round-button-container padded">

    <!-- ACTION BUTTONS -->
    <%= link_to edit_query_path(@query), class: 'round-button-new-element-link' do %>
      <div class="round-button round-button-top round-button-right bg-blue flex-center">
        <p><i class="fa fa-cog" aria-hidden="true"></i></p>
        <div class="round-button-new-element bg-blue">
          Modifier la question
        </div>
      </div>
    <% end %>
    <%= link_to query_path(@query), method: :delete, class: 'round-button-new-element-link' do %>
      <div class="round-button round-button-center round-button-right bg-red flex-center">
        <p><i class="fa fa-minus" aria-hidden="true"></i></p>
        <div class="round-button-new-element bg-red">
          Supprimer la question
        </div>
      </div>
    <% end %>
    <% if @query.validated %> <!-- check if query is valid and add button accordingly -->
      <%= link_to query_path(@query, query: { validated: false }), method: :patch, class: 'round-button-new-element-link' do %>
        <div class="round-button round-button-bottom round-button-right bg-red flex-center">
          <p><i class="fa fa-ban" aria-hidden="true"></i></p>
          <div class="round-button-new-element bg-red">
            Invalider la question
          </div>
        </div>
      <% end %>
    <% elsif @query.choices.count >= 2 %> <!-- check if query has at least 2 choices and add button accordingly -->
      <%= link_to query_path(@query, query: { validated: true }), method: :patch, class: 'round-button-new-element-link' do %>
        <div class="round-button round-button-bottom round-button-right bg-green flex-center">
          <p><i class="fa fa-check" aria-hidden="true"></i></p>
          <div class="round-button-new-element bg-green">
            Valider la question
          </div>
        </div>
      <% end %>
    <% end %>
    <!-- ACTION BUTTONS -->


    <div class="section-title">
      <% if @query.description.length > 0 %>
        <p class='section-title-description'><%= @query.description %></p>
      <% else %>
        <p class="section-title-description">Aucune description fournie</p>
      <% end %>
      <p class='section-title-description truncated'>En savoir plus: <%= link_to @query.see_more, @query.see_more %></p>
    </div>
  </div>
</div>
<!-- BODY 1 -->

<!-- VALIDITY BANNER -->
<% if @query.validated %>
  <p class='text-center bg-green padded-sm'>Question validée <i class="fa fa-check-circle" aria-hidden="true"></i></p>
<% else %>
  <p class='text-center bg-red padded-sm'>En attente de validation <i class="fa fa-times-circle" aria-hidden="true"></i><br>(2 choix minimum pour pouvoir valider)</p>
<% end %>
<!-- VALIDITY BANNER -->

<!-- BODY 2 -->
<div class="container">
  <div class="padded">

    <% if choices.empty? %> <!-- check if query has choices associated -->
      <p>Aucun choix enregistré</p>
    <% else %>
      <% choices.each_with_index do |choice, index| %>

        <!-- CHOICE INSTANCE -->
        <div class="list-instance-container">
          <div class="list-instance-item list-instance-id">
            <%= index + 1 %>
          </div>
          <hr>
          <div class="list-instance-item list-instance-content">
            <%= choice.content %>
          </div>
          <hr>
          <div class="list-instance-item list-instance-actions">
            <%= link_to edit_choice_path(choice) do %>
              <i class="fa fa-pencil" aria-hidden="true" id="edit"></i>
            <% end %>
            <%= link_to choice_path(choice), method: :delete do %>
              <i class="fa fa-trash-o" aria-hidden="true" id="delete"></i>
            <% end %>
          </div>
        </div>
        <!-- CHOICE INSTANCE -->

      <% end %>
    <% end %>

    <!-- FORM new_choice -->
    <div class="padded-sm">
      <%= render "choices/inline_form" %>
    </div>
    <!-- FORM new_choice -->

  </div>
</div>
<!-- BODY 2 -->